version: '3'
services:
  ganache-cli:
    build:
      context: ./
      dockerfile: ./ganache-cli/Dockerfile
    image: "plasma-chamber-ganache-cli:develop"
    ports:
      - "8545:8545"
  deployer:
    build:
      context: ./
      dockerfile: ./deploy-contracts/Dockerfile
    image: "plasma-chamber-deploy-contracts:develop"
    command: sh ./wait.sh
#    environment:
#      - DEPLOYMENT_TARGET=dockercompose
    depends_on:
      - ganache-cli
  operator:
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
    image: "cryptoeconomicslab/plasma-chamber:development"
    ports:
      - "3000:3000"
    entrypoint: sh ./wait.sh /home/node/.npm-global/bin/layer2-operator
    volumes:
      - ./wait.sh:/wait.sh
    environment:
      - ROOTCHAIN_ADDRESS=0xeec918d74c746167564401103096d45bbd494b74
      - OPERATOR_PRIVATE_KEY=0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3
      - ROOTCHAIN_ENDPOINT=http://host.docker.internal:8545
    user: root
    depends_on:
      - ganache-cli
      - deployer

